# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'bryantcabrera_mobileforming' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bryantcabrera_mobileforming

  target 'bryantcabrera_mobileforming-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bryantcabrera_mobileformingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'GoogleMaps'
  pod 'GooglePlaces'
end

target 'bryantcabrera_mobileforming-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bryantcabrera_mobileforming-tvOS

  target 'bryantcabrera_mobileforming-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
